'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {Float,OrbitControls,Environment,Sparkles} from '@react-three/drei';
import {motion,AnimatePresence} from 'framer-motion';
import {useRef,useState} from 'react';
import * as THREE from 'three';

function Flower({x,y,z,scale=1,color='#ff6f91'}:{x:number;y:number;z:number;scale?:number;color?:string}){const g=useRef<THREE.Group>(null!);useFrame((s)=>{g.current.rotation.y=s.clock.elapsedTime*.35;g.current.rotation.z=Math.sin(s.clock.elapsedTime*1.2+x)*.06});return <Float speed={1.2} rotationIntensity={.15} floatIntensity={.35}><group ref={g} position={[x,y,z]} scale={scale}>{Array.from({length:8}).map((_,i)=><mesh key={i} rotation={[0,0,i*Math.PI/4]} position={[0,Math.sin(i*Math.PI/4)*.34,0]}><sphereGeometry args={[.34,.22,16]}/><meshStandardMaterial color={color} roughness={.28} metalness={.08}/></mesh>)}<mesh position={[0,0,0]}><sphereGeometry args={[.2,24,24]}/><meshStandardMaterial color="#ffd166" emissive="#ffb703" emissiveIntensity={.2}/></mesh><mesh position={[0,-.65,0]}><cylinderGeometry args={[.045,.06,1.2,12]}/><meshStandardMaterial color="#3b7d4f"/></mesh></group></Float>}
function Bouquet(){return <group>{[[-.8,.2,0],[0,.35,.1],[.8,.2,0],[-.45,.85,-.15],[.45,.85,-.1],[0,1.2,-.2]].map((p,i)=><Flower key={i} x={p[0]} y={p[1]} z={p[2]} scale={i>4?.78:1} color={i%3===0?'#ff5470':i%3===1?'#ff9fba':'#f7c6d9'}/>)}<mesh position={[0,-.55,0]} rotation={[0,0,0]}><coneGeometry args={[1.05,.9,5]}/><meshStandardMaterial color="#ead8bd" roughness={.75}/></mesh></group>}
export default function Home(){const [open,setOpen]=useState(false);return <main><div className="glow g1"/><div className="glow g2"/><header><span>01 · SANA</span><span>ÖZEL BİR BUKET</span></header><section className="hero"><div className="copy"><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="eyebrow">Küçük bir dijital sürpriz</motion.p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.15}}><i>Özür</i> dilerim.</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35}} className="lead">Bazı şeyleri kelimelerle anlatmak zor. O yüzden sana bu kez çiçeklerle anlatmak istedim.</motion.p><button onClick={()=>setOpen(true)}>Buketimi aç <span>↗</span></button></div><div className="scene"><Canvas camera={{position:[0,1.1,5.3],fov:38}}><ambientLight intensity={1.2}/><directionalLight position={[3,5,4]} intensity={2.5}/><pointLight position={[-3,2,2]} intensity={12} color="#ff8fab" distance={8}/><Environment preset="sunset"/><Bouquet/><Sparkles count={80} scale={5} size={2} speed={.25} color="#ffd6e0"/><OrbitControls enablePan={false} minDistance={4} maxDistance={7} autoRotate autoRotateSpeed={.7}/></Canvas><div className="hint">sürükle · çevir · keşfet</div></div></section><section className="bottom"><span>Bir buket, bin his.</span><span>♡</span><span>Senin için hazırlandı</span></section><AnimatePresence>{open&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}><motion.div className="card" initial={{scale:.85,y:30}} animate={{scale:1,y:0}} onClick={e=>e.stopPropagation()}><div className="mini">♥</div><h2>Özür dilerim.</h2><p>Kalbini kırdıysam gerçekten üzgünüm. Bazen doğru şeyi söylemek yerine susabiliyorum, bazen de anlatmak istediğim şeyi yanlış anlatıyorum. Ama şunu bilmeni istiyorum:</p><strong>Sen benim için çok değerlisin.</strong><p>Bu çiçekler de küçük bir hatırlatma olsun. İyi ki varsın. 🤍</p><button onClick={()=>setOpen(false)}>Bunu kalbimde saklıyorum</button></motion.div></motion.div></AnimatePresence>}</main>}